# Page tree and navigation
nav:
- Home: index.md
- About:
  - About this project: about/site.md
  - About the author: about/author.md
- SRE:
  - The Manifesto: sre/manifesto.md
  - The Practices: sre/practices.md
  - Signatories and Supporters: sre/supporters.md
  - Manifesto Revisions: sre/revisions.md

# Theme
# theme: readthedocs
theme:
  name: material
  # Static files
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    # - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: darkblue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: slate
      accent: darkgreen
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/sre-knot.ico
  logo: images/sre-knot.png
markdown_extensions:
  - meta
  - md_in_html

# Project information
site_name: The SRE Manifesto
site_url: https://www.sre-manifesto.org
site_author: Rod Anami
site_description: >-
  The SRE Manifesto is a collection of principles, values and practices that guide the work of SREs.

# Repository
repo_name: Feedback/Issues
repo_url:  https://github.com/rod4n4m1/sre-manifesto/issues
edit_uri: ""

# Copyright statement in Footer
copyright:  The SRE Manifesto © 2022-2024 by its authors and collaborators is licensed under CC BY 4.0.